### ISSUE TITLE
sstableloader fails with uppercase KS trying to load into lowercase when importing few years old cassandra

### ISSUE THREAD

**Issue by matkor** [scylladb/scylla-tools-java#126]
I tried to follow
https://docs.scylladb.com/operating-scylla/procedures/cassandra_to_scylla_migration_process/
to migrate cassandra to scylladb.
Cassandra instance contains uppercase KS/CF names like: FooBar/Beef, but sstableloader fails trying to load into lowercase KS:
```
sstableloader -d 10.30.3.125   FooBar/Beef-4309ff40796311e589fde949b7b753ef/
com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'foobar' does not exist
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:294)
        at com.scylladb.tools.BulkLoader$CQLClient.<init>(BulkLoader.java:370)
        at com.scylladb.tools.BulkLoader.main(BulkLoader.java:1333)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'foobar' does not exist
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:147)
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:198)
        at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:50)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:852)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:686)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1087)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1010)
        at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
        at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at com.datastax.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
        at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by penberg** [comment]
We are probably forgetting to quote keyspace name when generating the CQL statements in our sstableloeader.

/cc @elcallio @psarna

**Comment by slivne** [comment]
@elcallio can you have a  look.

**Comment by tarzanek** [comment]
quick and dirty patch (usable to several GB, to 100GB one would need a rewrite to faster patch)
```
git diff src/java/com/scylladb/tools/BulkLoader.java src/java/org/apache/cassandra/io/sstable/Descriptor.java src/java/com/scylladb/tools/SSTableToCQL.java
diff --git a/src/java/com/scylladb/tools/BulkLoader.java b/src/java/com/scylladb/tools/BulkLoader.java
index 9bc8ebbcbd..2f0eed0bd3 100644
--- a/src/java/com/scylladb/tools/BulkLoader.java
+++ b/src/java/com/scylladb/tools/BulkLoader.java
@@ -1329,7 +1329,7 @@ public class BulkLoader {
                 dir = dir.getParentFile().getParentFile();
             }

-            final String keyspace = dir.getParentFile().getName();
+            final String keyspace = "\""+dir.getParentFile().getName()+"\"";
             final CQLClient client = new CQLClient(options, keyspace);

             // Hack. Must do because Range mangling code in cassandra is
diff --git a/src/java/com/scylladb/tools/SSTableToCQL.java b/src/java/com/scylladb/tools/SSTableToCQL.java
index 7e3a7fa95e..0dd1dff390 100644
--- a/src/java/com/scylladb/tools/SSTableToCQL.java
+++ b/src/java/com/scylladb/tools/SSTableToCQL.java
@@ -914,9 +914,13 @@ public class SSTableToCQL {

         protected void writeColumnFamily(StringBuilder buf) {
             buf.append(' ');
+            buf.append('"');
             buf.append(cfMetaData.ksName);
+            buf.append('"');
             buf.append('.');
+            buf.append('"');
             buf.append(cfMetaData.cfName);
+            buf.append('"');
             buf.append(' ');
         }
     }
diff --git a/src/java/org/apache/cassandra/io/sstable/Descriptor.java b/src/java/org/apache/cassandra/io/sstable/Descriptor.java
index 1f7e67f520..bd60bd0d64 100644
--- a/src/java/org/apache/cassandra/io/sstable/Descriptor.java
+++ b/src/java/org/apache/cassandra/io/sstable/Descriptor.java
@@ -313,7 +313,7 @@ public class Descriptor
         }
         assert tokenStack.isEmpty() : "Invalid file name " + name + " in " + directory;

-        return Pair.create(new Descriptor(version, parentDirectory, ksname, cfname, generation, fmt,
+        return Pair.create(new Descriptor(version, parentDirectory, "\""+ksname+"\"", "\""+cfname+"\"", generation, fmt,
                                           // _assume_ version from version
                                           Component.digestFor(version.uncompressedChecksumType())),
                            component);
```

**Comment by elcallio** [comment]
I don't get it. The OP example (as far as I can discern) works fine for me on current scylla. (I.e. create ks/cf with camel case, then import tables - either camel-cased dirnames or not). 

What version of scylla tools was this run with? It really sounds like a driver issue, since it should pretty much be up to the driver to do any escaping if needed.

**Comment by tarzanek** [comment]
I was able to repro on (updated) centos 7.7 + scylla 3.1.2

**Comment by tarzanek** [comment]
repro steps:
save below and run cqlsh -f <filename>
```
create keyspace "FooBar" WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};

CREATE TABLE "FooBar"."BarFoo" (
    hash text PRIMARY KEY,
    id text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';


insert INTO "FooBar"."BarFoo"(hash,id) values('record1','id1');
insert INTO "FooBar"."BarFoo"(hash,_id) values('record2','id2');

select * from "FooBar"."BarFoo";
```
`nodetool flush`
move aside data dir for this keyspace
`cqlsh -e "truncate \"FooBar\".\"BarFoo\";"`
try to load the sstables from directory put aside, e.g.:
`sstableloader -d 127.0.0.1   \"FooBar\"/\"BarFoo\"-259d2fe0312911ea85b2000000000000/`

**Comment by elcallio** [comment]
That has zero to do with camel casing. That is having explicit " in the names. And adding hardcoded " into names is certainly not gonna translate well with non-" using (normal) names.

**Comment by elcallio** [comment]
Note also that afaik both scylla and cassandra will create the file names for \"FooBar\" as FooBar (i.e. eliminate the quotes. Trying to synthesize back said quite quotes cannot really be done. I think this is a weakness shared with the original bulkloader in cassandra, from which the derivation of keyspace name from path is inherited. 
Otoh, renaming the directories and files to be loaded to include quotes should fix the quote issue.

**Comment by penberg** [comment]
@elcallio If you don't quote the identifiers, Scylla and Cassandra treat the names as case-insensitive, no? The `keyspace` passed to `CQLClient` constructor is just forwarded to `Cluster.connect()`. If the name of the keyspace is not quoted, it is treated as case-insensitive. How would the driver know when to quote and when to not? It's really the _caller_ that's supposed to define the keyspace name (and if it's case sensitive or insensitive)...

**Comment by matkor** [comment]
> What version of scylla tools was this run with? 

Most likely it was Ubuntu's:
```
dpkg -s scylla-tools
```
Version: 3.1.2-20191127.915d16dc8f-1

> It really sounds like a driver issue, since it should pretty much be up to the driver to do any escaping if needed.

What you mean by driver?

> I don't get it. The OP example (as far as I can discern) works fine for me on current scylla. (I.e. create ks/cf with camel case, then import tables - either camel-cased dirnames or not).

Thinks which are/may be different in our case:
1. problem ks/cf was created using pycassa (so thrift) and may be compact storage.
2. problem ks/cf is empty (no cf files in dir)

P.S.
Anyway we had to solve problem on app level, and might not be able to repeat that import. :(

**Comment by elcallio** [comment]
Ok, now I see what you are getting at. I was confused by the usage of explicit quotes in filenames above. Yes, it seems cql has this weird way of distinguishing case sensitive names. But it should be easily fixed by taking this into account in the metadata query (via driver).

**Comment by tarzanek** [comment]
yes, sorry for explicit quotes, was a futile attempt to force loader to use directory names with quotes (didn't work of course)
I will fix the quotes in example to the ones I used
