### ISSUE TITLE
sstableloader fails to work with ICS sstables

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-tools-java#131]
scenario: trying to run sstableloader on an ICS table with previously created ICS sstables, it fails with:
```
$ /home/yarongilor/git/enterprise/scylla-enterprise/resources/cassandra/bin/sstableloader -d 127.0.0.1 /tmp/tmpCY7uqb/keyspace1/standard1
WARN  19:09:30,972 dclocal_read_repair_chance and read_repair_chance table options have been deprecated and will be removed in version 4.0
org.apache.cassandra.exceptions.ConfigurationException: Properties specified [sstable_size_in_mb] are not understood by IncrementalCompactionStrategy
at org.apache.cassandra.schema.CompactionParams.validate(CompactionParams.java:148)
at org.apache.cassandra.schema.TableParams.validate(TableParams.java:139)
at org.apache.cassandra.cql3.statements.TableAttributes.validate(TableAttributes.java:55)
at org.apache.cassandra.cql3.statements.CFProperties.validate(CFProperties.java:35)
at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:216)
at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:689)
at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1519)
at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1336)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
org.apache.cassandra.exceptions.ConfigurationException: Properties specified [sstable_size_in_mb] are not understood by IncrementalCompactionStrategy
at org.apache.cassandra.schema.CompactionParams.validate(CompactionParams.java:148)
at org.apache.cassandra.schema.TableParams.validate(TableParams.java:139)
at org.apache.cassandra.cql3.statements.TableAttributes.validate(TableAttributes.java:55)
at org.apache.cassandra.cql3.statements.CFProperties.validate(CFProperties.java:35)
at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:216)
```

**Comment by yarongilor** [comment]
issue should be moved to enterprise tools java

**Comment by yarongilor** [comment]
opened https://github.com/scylladb/scylla-enterprise-tools-java/issues/20
