### ISSUE TITLE
sstableloader does not work on AWS

### ISSUE THREAD

**Issue by rookie7799** [scylladb/scylla-tools-java#160]
1. Created single node cluster using "ScyllaDB 4.0.0 (ami-09ae7080d6e842625)" 
2. Edited /etc/scylla/scylla.yaml to my needs.
3. Started scylla-server
4. Re-created the schema from cassandra, i can see the table, can insert / select etc.

And the problem starts - trying to load sstable using sstableloader:

```
sstableloader -v -d 10.100.1.12 /mnt/storage/cassandra/snapshots/cas1/ase/2019_08_13_twitter-39832d72c77511e99920bf701ea7724f/
===== Using optimized driver!!! =====
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.
```
Notice that it does not even print any debug info ...

I've tried many things and then finally I decided to COPY /etc/scylla/scylla.yaml as /etc/scylla/cassandra.yaml ... and now we have debug info: 

```
sstableloader -v -d 10.100.1.12 /mnt/storage/cassandra/snapshots/cas1/ase/2019_08_13_twitter-39832d72c77511e99920bf701ea7724f/
00:15:28.240 [main] DEBUG c.d.driver.core.GuavaCompatibility - Error while checking existence of method Futures.transformAsync
java.lang.NoSuchMethodException: com.google.common.util.concurrent.Futures.transformAsync(com.google.common.util.concurrent.ListenableFuture, com.google.common.util.concurrent.AsyncFunction, java.util.concurrent.Executor)
        at java.lang.Class.getMethod(Class.java:1786) ~[na:1.8.0_252]
        at com.datastax.driver.core.GuavaCompatibility.methodExists(GuavaCompatibility.java:330) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.GuavaCompatibility.isGuava_19_0_OrHigher(GuavaCompatibility.java:295) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:184) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:59) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.PoolingOptions.<clinit>(PoolingOptions.java:137) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.scylladb.tools.BulkLoader$CQLClient.<init>(BulkLoader.java:313) [scylla-tools-4.0.0-20200505.5a4974fcc4.jar:4.0.0-20200505.5a4974fcc4]
        at com.scylladb.tools.BulkLoader.main(BulkLoader.java:1339) [scylla-tools-4.0.0-20200505.5a4974fcc4.jar:4.0.0-20200505.5a4974fcc4]
00:15:28.271 [main] INFO  c.d.driver.core.GuavaCompatibility - Detected Guava < 19 in the classpath, using legacy compatibility layer
00:15:28.316 [main] INFO  com.datastax.driver.core - DataStax Java driver 3.7.1-scylla-2 for Apache Cassandra
00:15:28.318 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1
00:15:28.318 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60
00:15:28.340 [main] INFO  c.datastax.driver.core.LZ4Compressor - Using LZ4Factory:JNI
00:15:28.341 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
00:15:28.343 [main] DEBUG com.datastax.driver.core.Native - Could not load JNR C Library, native system calls through this library will not be available
java.lang.NoClassDefFoundError: jnr/ffi/LibraryLoader
        at com.datastax.driver.core.Native$LibCLoader.<clinit>(Native.java:104) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Native.isGettimeofdayAvailable(Native.java:189) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.ClockFactory.newInstance(Clock.java:56) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.AbstractMonotonicTimestampGenerator.<init>(AbstractMonotonicTimestampGenerator.java:42) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.LoggingMonotonicTimestampGenerator.<init>(LoggingMonotonicTimestampGenerator.java:53) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:55) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:37) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.policies.Policies.defaultTimestampGenerator(Policies.java:123) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.policies.Policies$Builder.build(Policies.java:287) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1357) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster.<init>(Cluster.java:164) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:230) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1374) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.scylladb.tools.BulkLoader$CQLClient.<init>(BulkLoader.java:370) [scylla-tools-4.0.0-20200505.5a4974fcc4.jar:4.0.0-20200505.5a4974fcc4]
        at com.scylladb.tools.BulkLoader.main(BulkLoader.java:1339) [scylla-tools-4.0.0-20200505.5a4974fcc4.jar:4.0.0-20200505.5a4974fcc4]
Caused by: java.lang.ClassNotFoundException: jnr.ffi.LibraryLoader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_252]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_252]
        ... 15 common frames omitted
00:15:28.343 [main] INFO  c.datastax.driver.core.ClockFactory - Using java.lang.System clock to generate timestamps.
00:15:28.344 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 4
===== Using optimized driver!!! =====
00:15:28.356 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [/10.100.1.12:9042]
00:15:28.373 [main] DEBUG c.d.s.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
00:15:28.388 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - -Dio.netty.noUnsafe: false
00:15:28.388 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - Java version: 8
00:15:28.389 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
00:15:28.389 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
00:15:28.389 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available
00:15:28.390 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - direct buffer constructor: available
00:15:28.390 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - java.nio.Bits.unaligned: available, true
00:15:28.390 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
00:15:28.390 [main] DEBUG c.d.s.n.u.i.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
00:15:28.390 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - sun.misc.Unsafe: available
00:15:28.391 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
00:15:28.391 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
00:15:28.391 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
00:15:28.391 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1908932608 bytes
00:15:28.391 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
00:15:28.392 [main] DEBUG c.d.s.n.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
00:15:28.396 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false
00:15:28.397 [main] INFO  com.datastax.driver.core.NettyUtil - Detected shaded Netty classes in the classpath; native epoll transport will not work properly, defaulting to NIO.
00:15:28.399 [main] DEBUG c.d.s.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
00:15:28.405 [main] DEBUG c.d.s.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
00:15:28.405 [main] DEBUG c.d.s.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
00:15:28.411 [main] DEBUG c.d.s.n.u.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
00:15:28.421 [main] DEBUG c.d.s.n.util.ResourceLeakDetector - -Dcom.datastax.shaded.netty.leakDetection.level: simple
00:15:28.421 [main] DEBUG c.d.s.n.util.ResourceLeakDetector - -Dcom.datastax.shaded.netty.leakDetection.targetRecords: 4
00:15:28.422 [main] DEBUG c.d.s.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: com.datastax.shaded.netty.util.ResourceLeakDetector@53ca01a2
00:15:28.426 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true
00:15:28.496 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] preparing to open 1 new connections, total = 1
00:15:28.498 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
00:15:28.498 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000
00:15:28.498 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5
00:15:28.502 [main] DEBUG c.d.s.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
00:15:28.502 [main] DEBUG c.d.s.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
00:15:28.518 [main] DEBUG c.d.s.n.b.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
00:15:28.549 [main] DEBUG c.d.shaded.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
00:15:28.549 [main] DEBUG c.d.shaded.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
00:15:28.550 [main] DEBUG c.d.shaded.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
00:15:28.612 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-1, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.628 [cluster1-nio-worker-0] DEBUG c.d.shaded.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 32768
00:15:28.628 [cluster1-nio-worker-0] DEBUG c.d.shaded.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
00:15:28.628 [cluster1-nio-worker-0] DEBUG c.d.shaded.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
00:15:28.628 [cluster1-nio-worker-0] DEBUG c.d.shaded.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
00:15:28.633 [cluster1-nio-worker-0] DEBUG c.d.s.netty.buffer.AbstractByteBuf - -Dcom.datastax.shaded.netty.buffer.bytebuf.checkAccessible: true
00:15:28.633 [cluster1-nio-worker-0] DEBUG c.d.s.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: com.datastax.shaded.netty.util.ResourceLeakDetector@64837f25
00:15:28.642 [cluster1-nio-worker-0] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.NATIVE_TRANSPORT_MAX_FRAME_SIZE_IN_MB is undefined, using default value 256
00:15:28.643 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-1, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.646 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] Refreshing node list and token map
00:15:28.673 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] Refreshing schema
00:15:28.764 [main] DEBUG c.d.d.c.ReplicationStrategy$NetworkTopologyStrategy - Computing token to replica map for keyspace: ase.
00:15:28.767 [main] DEBUG c.d.d.c.ReplicationStrategy$NetworkTopologyStrategy - Token to replica map computation for keyspace ase completed in 2 milliseconds
00:15:28.788 [main] DEBUG com.datastax.driver.core.Host.STATES - [Control connection] established to /10.100.1.12:9042
00:15:28.788 [main] INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'us-east' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
00:15:28.789 [main] INFO  com.datastax.driver.core.Cluster - New Cassandra host /10.100.1.12:9042 added
00:15:28.793 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.CHECK_IO_DEADLOCKS is undefined, using default value true
00:15:28.796 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] preparing to open 1 new connections, total = 2
00:15:28.798 [cluster1-nio-worker-2] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-2, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.802 [cluster1-nio-worker-2] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-2, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.803 [main] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] preparing to open 6 new connections, total = 8
00:15:28.806 [cluster1-nio-worker-3] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-3, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.809 [cluster1-nio-worker-5] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-5, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.810 [cluster1-nio-worker-3] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-3, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.812 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-8, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.812 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-7, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.814 [cluster1-nio-worker-4] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-4, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.815 [cluster1-nio-worker-5] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-5, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.816 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-6, inFlight=0, closed=false] Connection established, initializing transport
00:15:28.817 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-8, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.823 [cluster1-nio-worker-7] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-7, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.823 [cluster1-nio-worker-4] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-4, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.827 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-6, inFlight=0, closed=false] Transport initialized, connection ready
00:15:28.829 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-4, inFlight=0, closed=true] closing connection
00:15:28.829 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-4, inFlight=0, closed=true] closed, remaining = 7
00:15:28.830 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-6, inFlight=0, closed=true] closing connection
00:15:28.830 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-6, inFlight=0, closed=true] closed, remaining = 6
00:15:28.831 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-7, inFlight=0, closed=true] closing connection
00:15:28.831 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Host.STATES - [/10.100.1.12:9042] Connection[/10.100.1.12:9042-7, inFlight=0, closed=true] closed, remaining = 5
00:15:28.832 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Session - Added connection pool for /10.100.1.12:9042
00:15:28.840 [cluster1-nio-worker-6] DEBUG com.datastax.driver.core.Connection - Connection[/10.100.1.12:9042-6, inFlight=0, closed=true] has already terminated
00:15:28.926 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
00:15:28.926 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
00:15:28.926 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.

```

I don't understand why sstableloader is required to have "cassandra.yaml" to even start printing anything ... but ok...

Still, nothing is being inserted. The snapshot contains data from Cassandra 3.11.

Any ideas?

Thanks!

**Comment by fruch** [comment]
1. Can you share example of the schema being used ? and a sample of the data ?
2. Did you tried `nodetool refresh` ? https://docs.scylladb.com/operating-scylla/nodetool-commands/refresh/

**Comment by fruch** [comment]
can you share the `/etc/scylla/scylla.yaml` you are using ?

**Comment by fruch** [comment]
@psarna @elcallio, any idea what we are missing here ?

**Comment by rookie7799** [comment]
> can you share the `/etc/scylla/scylla.yaml` you are using ?

Added to the main description.

**Comment by rookie7799** [comment]
> 1. Can you share example of the schema being used ? and a sample of the data ?
> 2. Did you tried `nodetool refresh` ? https://docs.scylladb.com/operating-scylla/nodetool-commands/refresh/

```
CREATE KEYSPACE ase WITH replication = {'class': 'NetworkTopologyStrategy', 'us-east': '1' }  AND durable_writes = false;
CREATE TABLE ase."2019_08_13_twitter" (
    profile_id bigint,
    affinity_id int,
    PRIMARY KEY (profile_id, affinity_id)
) WITH CLUSTERING ORDER BY (affinity_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'sstable_compression':'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99PERCENTILE';

insert into ase."2019_08_13_twitter" (profile_id,affinity_id) values (1,1);
```

About to try nodetool refresh.

**Comment by rookie7799** [comment]
Copied aa-*.db files over into ./upload/ dir and ran:

```
nodetool refresh -- ase 2019_08_13_twitter
nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/ase' failed: Failed to load new sstables: sstables::malformed_sstable_exception (invalid version for file aa-875-bti-CompressionInfo.db. Name doesn't match any known version.)

```

**Comment by fruch** [comment]
I think we can only read `big` format tables
https://stackoverflow.com/questions/58870769/better-understand-sstables-formats-big-vs-bti

from which version are you copying this data ? a datastax version ? or open-source cassandra 3.11 ?

**Comment by rookie7799** [comment]
> I think we can only read `big` format tables
> https://stackoverflow.com/questions/58870769/better-understand-sstables-formats-big-vs-bti
> 
> from which version are you copying this data ? a datastax version ? or open-source cassandra 3.11 ?

Datastax 6.5

**Comment by fruch** [comment]
I'll can check tomorrow with more people, but I think we can't read Datastax proprietary format directly.
and need to migrate using something like https://github.com/scylladb/scylla-migrator
while both are cluster are up and running.

**Comment by fruch** [comment]
try using datastax own tool, to create a "mc" "big" format sstables:
https://docs.datastax.com/en/dse/6.0/dse-dev/datastax_enterprise/tools/toolsSStables/ToolsSSTabledowngrade.html

**Comment by rookie7799** [comment]
I think we can try the migrator approach but I cannot alter production tables at this time.

**Comment by fruch** [comment]
> I think we can try the migrator approach but I cannot alter production tables at this time.

Again I never used this downgrade command, but it seems to make a copy of the tables, not changing them inplace, at least what the examples there are showing.

I guess it would be safe to test it on its own cluster/node and on production.
