### ISSUE TITLE
cassandra-stress can keep running even if thread had failed

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-tools-java#168]
Steps to reproduce are following:
1. Run c-s with 40 threads:
```
cassandra-stress read  cl=QUORUM duration=240m -schema keyspace=keyspace1 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 
native -rate threads=40 -pop seq=1..20971520 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5 -node 10.0.2.221 -errors skip-unsupported-columns

```
2. Make one thread to fail, in this test thread failed due to the CQL error of QUORUM inconsistency

Result:
c-s hung for 1hour till produced:
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)

Test-id: 6bb58cd8-dd28-4afd-8a0d-dbc73e2489a4

[c-s.log](https://github.com/scylladb/scylla-tools-java/files/4677672/c-s.log)

**Comment by dkropachev** [comment]
Another occasion with debug output:
[Uploading cassandra-stress-l0-c0-k1-01665285-0ef1-408f-9325-484098e432a4.log…]()

**Comment by fruch** [comment]
happened during testing of 2023.1

## Installation details

Kernel Version: 5.15.0-1036-aws
Scylla version (or git commit hash): `2023.1.0~rc6-20230517.ca8d6a0d4fa7` with build-id `3c3e22ad787d01bbfda9da05aa4a62beb1004157`




Cluster size: 3 nodes (i3en.large)

Scylla Nodes used in this run:
- longevity-schemachanges-3h-2023-1-db-node-7db11cad-3 (34.242.98.148 | 10.4.1.139) (shards: 2)
- longevity-schemachanges-3h-2023-1-db-node-7db11cad-2 (52.16.26.237 | 10.4.3.43) (shards: 2)
- longevity-schemachanges-3h-2023-1-db-node-7db11cad-1 (54.247.60.78 | 10.4.1.101) (shards: 2)


OS / Image: `ami-094190108e73c7d8e` (aws: eu-west-1)

Test: `longevity-schema-changes-3h-test`
Test id: `7db11cad-2048-48e0-8e19-c416184fa6d2`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/audit/longevity-schema-changes-3h-test`
Test config file(s):

- [longevity-schema-changes-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ef1612e92b06a90d9bb11b960b8b04b679b8f131/test-cases/longevity/longevity-schema-changes-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 7db11cad-2048-48e0-8e19-c416184fa6d2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7db11cad-2048-48e0-8e19-c416184fa6d2)
- Show all stored logs command: `$ hydra investigate show-logs 7db11cad-2048-48e0-8e19-c416184fa6d2`


## Logs:
- **db-cluster-7db11cad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/db-cluster-7db11cad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/db-cluster-7db11cad.tar.gz)
- **sct-runner-events-7db11cad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/sct-runner-events-7db11cad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/sct-runner-events-7db11cad.tar.gz)
- **sct-7db11cad.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/sct-7db11cad.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/sct-7db11cad.log.tar.gz)
- **monitor-set-7db11cad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/monitor-set-7db11cad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/monitor-set-7db11cad.tar.gz)
- **loader-set-7db11cad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/loader-set-7db11cad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/loader-set-7db11cad.tar.gz)
- **parallel-timelines-report-7db11cad.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/parallel-timelines-report-7db11cad.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7db11cad-2048-48e0-8e19-c416184fa6d2/20230629_111120/parallel-timelines-report-7db11cad.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/audit/job/longevity-schema-changes-3h-test/3/)
[Argus](https://argus.scylladb.com/test/32eea484-9fbe-48bd-a0a8-ed9e202706ad/runs?additionalRuns[]=7db11cad-2048-48e0-8e19-c416184fa6d2)
</details>

**Comment by fruch** [comment]
happened also in multi-dc case:
https://github.com/scylladb/scylladb/issues/13667

seems like it's happening when there lots of error happening during the run

**Comment by roydahan** [comment]
@mykaul can you please help us assign this issue, it makes our longevities hard to investigate.

**Comment by dkropachev** [comment]
@roydahan, @mykaul, i will take a look at it

**Comment by roydahan** [comment]
@dkropachev any chance you looked at this one?

**Comment by Bouncheck** [comment]
I believe this happens because cassandra-stress by design always waits the full duration time before checking the threads. In StressAction.java:267 (in run method) there's the following code:
```
if (durationUnits != null)
        {
            Uninterruptibles.sleepUninterruptibly(duration, durationUnits);
            workManager.stop();
        }
```
This simply waits the full duration before doing anything else.
At the same time the `Consumer` instances once they hit the default limit of 10 errors (on a single operation; in a row) they just fail and don't request next operations. If at least one consumer/thread failed then the final result will also be a failure.
Lines like this one are likely evidence of thread failing:
```
java.io.IOException: Operation x10 on key(s) [324e354d304b30343630]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
Operation x10 here means that operation has failed 10 times. If the threshold was set to 20 then lines will say x20.
If settings were not deliberately set to ignore errors then this IOException is a result of rethrowing on Operation level. Then it's caught on Consumer level and further work is abandoned.

**Comment by roydahan** [comment]
In our case none of the threads fails.
