### ISSUE TITLE
nodetool flush: java.lang.NoClassDefFoundError: com/google/common/collect/ArrayListMultimap

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-tools-java#233]
*Installation details*
Scylla version (or git commit hash):
- scylla-tools all 4.3.2-0.20210301.5cdc1fa66-1
- scylla-tools (4.4~rc3-0.20210304.c2d924757-1)
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

### Description

The 'nodetool flush' in Step4 (Verify data during mixed cluster mode) failed.
fill_db_data (https://github.com/scylladb/scylla-cluster-tests/blob/branch-2020.1/sdcm/fill_db_data.py) test executed a series queries to verify the data.

The 'nodetool flush' is a sub query of range_tombstones_test test. It will executed 'nodetool flush' on all 4 nodes one by one.

In Job#19, 

Node2 was Updated: 4.4.rc2
Node3 was Updated -> Rollbacked: 4.3.2
Node1, Node4 were still : 4.3.2

Nodetool flush' of Node1,Node2,Node3 all succeeded

Only 'nodetool flush' on Node4 failed. 'Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ArrayListMultimap'

```
< t:2021-03-04 19:06:38,059 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "sudo  nodetool flush"...

2021-03-04 19:06:38,083  Using /etc/scylla/scylla.yaml as the config file
2021-03-04 19:06:38,725  Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ArrayListMultimap
2021-03-04 19:06:38,726  	at io.airlift.command.model.MetadataLoader.mergeOptionSet(MetadataLoader.java:207)
2021-03-04 19:06:38,727  	at io.airlift.command.model.MetadataLoader.access$700(MetadataLoader.java:27)
2021-03-04 19:06:38,727  	at io.airlift.command.model.MetadataLoader$InjectionMetadata.compact(MetadataLoader.java:252)
2021-03-04 19:06:38,727  	at io.airlift.command.model.MetadataLoader$InjectionMetadata.access$600(MetadataLoader.java:242)
2021-03-04 19:06:38,728  	at io.airlift.command.model.MetadataLoader.loadInjectionMetadata(MetadataLoader.java:112)
2021-03-04 19:06:38,729  	at io.airlift.command.model.MetadataLoader.loadCommand(MetadataLoader.java:86)
2021-03-04 19:06:38,729  	at io.airlift.command.Cli.<init>(Cli.java:74)
2021-03-04 19:06:38,730  	at io.airlift.command.Cli.<init>(Cli.java:40)
2021-03-04 19:06:38,730  	at io.airlift.command.Cli$CliBuilder.build(Cli.java:246)
2021-03-04 19:06:38,730  	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:173)
2021-03-04 19:06:38,730  Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ArrayListMultimap
2021-03-04 19:06:38,730  	at java.net.URLClassLoader$1.run(URLClassLoader.java:371)
2021-03-04 19:06:38,730  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2021-03-04 19:06:38,730  	at java.security.AccessController.doPrivileged(Native Method)
2021-03-04 19:06:38,732  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2021-03-04 19:06:38,733  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2021-03-04 19:06:38,733  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2021-03-04 19:06:38,733  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2021-03-04 19:06:38,733  	... 10 more
2021-03-04 19:06:38,733  Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
2021-03-04 19:06:38,733  	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:432)
2021-03-04 19:06:38,733  	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
2021-03-04 19:06:38,734  	at sun.misc.Resource.getBytes(Resource.java:124)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:463)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2021-03-04 19:06:38,736  	... 16 more
2021-03-04 19:06:38,737  Error executing command: "sudo  nodetool flush"; Exit status: 1

```

### Test info

test id: 083c3307-37eb-42aa-b941-56afc2d68440
test job: https://jenkins.scylladb.com/job/scylla-4.4/job/rolling-upgrade/job/rolling-upgrade-ubuntu20.04-test/19

db log: https://cloudius-jenkins-test.s3.amazonaws.com/083c3307-37eb-42aa-b941-56afc2d68440/20210304_191539/db-cluster-083c3307.zip
sct log: https://cloudius-jenkins-test.s3.amazonaws.com/083c3307-37eb-42aa-b941-56afc2d68440/20210304_191539/sct-runner-083c3307.zip 
monitor log: https://cloudius-jenkins-test.s3.amazonaws.com/083c3307-37eb-42aa-b941-56afc2d68440/20210304_191539/monitor-set-083c3307.zip
loader log: https://cloudius-jenkins-test.s3.amazonaws.com/083c3307-37eb-42aa-b941-56afc2d68440/20210304_191539/loader-set-083c3307.zip

### Subtest range_tombstones_test in fill_db_data.py

```
        # range_tombstones_test: Test deletion by 'composite prefix' (range tombstones)
        {
            'create_tables': ["""CREATE TABLE range_tombstones_test (
                            k int,
                            c1 int,
                            c2 int,
                            v1 int,
                            v2 int,
                            PRIMARY KEY (k, c1, c2)
                        );"""],
            'truncates': [],
            'inserts': ["INSERT INTO range_tombstones_test (k, c1, c2, v1, v2) VALUES (%d, %d, %d, %d, %d)" % (
                i, j, k, (i * 4) + (j * 2) + k, (i * 4) + (j * 2) + k) for i in range(0, 5) for j in range(0, 2)
                for k
                in range(0, 2)],
            'queries': ["SELECT v1, v2 FROM range_tombstones_test where k = %d" % 0,
                        "SELECT v1, v2 FROM range_tombstones_test where k = %d" % 1,
                        "SELECT v1, v2 FROM range_tombstones_test where k = %d" % 2,
                        "SELECT v1, v2 FROM range_tombstones_test where k = %d" % 3,
                        "SELECT v1, v2 FROM range_tombstones_test where k = %d" % 4,
                        "DELETE FROM range_tombstones_test WHERE k = %d AND c1 = 0" % 0,
                        "DELETE FROM range_tombstones_test WHERE k = %d AND c1 = 0" % 1,
                        "DELETE FROM range_tombstones_test WHERE k = %d AND c1 = 0" % 2,
                        "DELETE FROM range_tombstones_test WHERE k = %d AND c1 = 0" % 3,
                        "DELETE FROM range_tombstones_test WHERE k = %d AND c1 = 0" % 4,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 0,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 1,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 2,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 3,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 4,
                        "#REMOTER_RUN sudo nodetool flush",
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 0,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 1,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 2,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 3,
                        "SELECT v1, v2 FROM range_tombstones_test WHERE k = %d" % 4],
```

/CC @roydahan @juliayakovlev

**Comment by roydahan** [comment]
@amoskong do we see any error on scylla side? (db log)

**Comment by amoskong** [comment]
> @amoskong do we see any error on scylla side? (db log)

No. There were only some regular compaction log from all db nodes before the flush fail.
And there is no any log from all db nodes after flush fail occurred.

The CRITICAL event of c-s read workload fail (-1) was sent after 'flush' fail, but the last normal output from the workload was before 'flush' fail.

And I didn't see 'power off' in all instances.

So we need to understand the meaning of `java.lang.ClassNotFoundException: com.google.commo
n.collect.ArrayListMultimap`, `java.lang.ClassNotFoundException: com.google.commo
n.collect.ArrayListMultimap`, `java.net.URLClassLoader$1.run(URLClassLoader.java:369)`.

----

### Start c-s read workload:
< t:2021-03-04 19:01:48,564 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "echo TAG: loader_idx:0-cpu_idx:0-keyspace_id
x:1; STRESS_TEST_MARKER=FW9ATDRLXA1YKX4QKLPA; cassandra-stress read no-warmup cl=QUORUM duration=60m -schema keyspace=keyspace1 'replication(factor
=3) compression=LZ4Compressor' -port jmx=6868 -mode cql3 native compression=lz4  user=cassandra password=cassandra -rate threads=1000 -pop seq=1..1
0100200 -log interval=5 -node 10.142.0.39 -errors skip-unsupported-columns"...


### last log of c-s read workload:
< t:2021-03-04 19:06:38,058 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > total,       9642547,   36468,   36468,   36468,    27.4,    
24.8,    59.9,    73.7,    96.9,   158.2,  285.0,  0.01541,      0,      0,       0,       0,       0,       0

### Succeed flush on Node3
< t:2021-03-04 19:06:38,059 f:base.py         l:140  c:RemoteCmdRunner      p:DEBUG > Command "sudo  nodetool flush" finished with status 0

### Started to flush on Node4
< t:2021-03-04 19:06:38,059 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "sudo  nodetool flush"...

< t:2021-03-04 19:06:38,114 f:connectionpool.py l:204  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.142.15.205:9093
< t:2021-03-04 19:06:38,116 f:connectionpool.py l:391  c:urllib3.connectionpool p:DEBUG > http://10.142.15.205:9093 "GET /api/v2/alerts?active=1 HT
TP/1.1" 200 1246
< t:2021-03-04 19:06:38,120 f:connectionpool.py l:204  c:urllib3.connectionpool p:DEBUG > Starting new HTTP connection (1): 10.142.15.205:9093
< t:2021-03-04 19:06:38,122 f:connectionpool.py l:391  c:urllib3.connectionpool p:DEBUG > http://10.142.15.205:9093 "GET /api/v2/alerts HTTP/1.1" 2
00 1246

### Flush failed on Node4
< t:2021-03-04 19:06:38,725 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ArrayListMultimap

< t:2021-03-04 19:06:38,748 f:common.py       l:1185 c:cassandra.cluster    p:DEBUG > Shutting down Cluster Scheduler
< t:2021-03-04 19:06:38,748 f:common.py       l:1185 c:cassandra.cluster    p:DEBUG > Shutting down control connection


< t:2021-03-04 19:06:38,751 f:tester.py       l:2038 c:UpgradeTest          p:INFO  > TearDown is starting...

**Comment by amoskong** [comment]
TransportException raised after flush error and TearDown started. It should be expected (normal)

```
2021-03-04 19:06:40,595 > com.datastax.driver.core.exceptions.TransportException: [rollupgrade-4-4-ubuntu-focal142.0.106:9042] Connection has been closed
2021-03-04 19:06:40,595 > ERROR 19:02:48,632 Unexpected error while querying rolling-upgrade-4-4-ubuntu-focal-db-node-083c3307-0-3.c.skilled-adapter-452.internal/10.142.0.106
2021-03-04 19:06:40,595 > com.datastax.driver.core.exceptions.ConnectionException: [rolling-upgrade-4-4-ubuntu-focal-db-node-083c3307-0-3.c.skilled-adapter-452.internal/10.142.0.106:9042] Pool is shutdown
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:841) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:437) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:525) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:2033) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1393) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:1988) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_282]
2021-03-04 19:06:40,595 >   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_282]
2021-03-04 19:06:40,595 >   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
2021-03-04 19:06:40,595 >   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
2021-03-04 19:06:40,595 >   at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
2021-03-04 19:06:40,595 >   at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
```

**Comment by amoskong** [comment]
There is no special hint in the monitor:  https://snapshot.raintank.io/dashboard/snapshot/q5lL41jw367JvJ0zyw8XhVknHnOrtUy1

- Missing read from node3 is higher, because it's just rollbacked.
- No series read/write timeout/unavailable before flush fail

**Comment by penberg** [comment]
The interesting part is the `java.io.EOFException: Unexpected end of ZLIB input stream` error -- the JVM attempted to load a class from one of the Jar files, but the Jar file is perhaps corrupt`

@elcallio Have you seen anything like this before?

```
2021-03-04 19:06:38,730  Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ArrayListMultimap
2021-03-04 19:06:38,730  	at java.net.URLClassLoader$1.run(URLClassLoader.java:371)
2021-03-04 19:06:38,730  	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2021-03-04 19:06:38,730  	at java.security.AccessController.doPrivileged(Native Method)
2021-03-04 19:06:38,732  	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2021-03-04 19:06:38,733  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2021-03-04 19:06:38,733  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2021-03-04 19:06:38,733  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2021-03-04 19:06:38,733  	... 10 more
2021-03-04 19:06:38,733  Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
2021-03-04 19:06:38,733  	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:432)
2021-03-04 19:06:38,733  	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
2021-03-04 19:06:38,734  	at sun.misc.Resource.getBytes(Resource.java:124)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:463)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2021-03-04 19:06:38,736  	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2021-03-04 19:06:38,736  	... 16 more
```

**Comment by elcallio** [comment]
File could be corrupted, or there could be an OOM somewhere in the 
native zip code, that has hidden itself until it became this. But 
corrupt file sounds more plausible.

Den 2021-03-17 kl. 13:20, skrev Pekka Enberg:

**Comment by penberg** [comment]
@elcallio @amoskong I checked 4.3-rc3 and it has the exact same `guava.jar` as we have in the source tree. @amoskong can you do something like `md5sum opt/scylladb/share/cassandra/lib/guava-18.0.jar`, and let's first rule out if the file is corrupt or not.

**Comment by slivne** [comment]
@amoskong if this reproduces - please leave the machines and allow calle/pekka to check

**Comment by amoskong** [comment]
> @elcallio @amoskong I checked 4.3-rc3 and it has the exact same `guava.jar` as we have in the source tree.
> 
> @amoskong can you do something like `md5sum opt/scylladb/share/cassandra/lib/guava-18.0.jar`, and let's first rule out if the file is corrupt or not.

Sorry I can't check this now. We only see this error once, the instances had been destroyed.

> @amoskong if this reproduces - please leave the machines and allow calle/pekka to check

It's difficult to reproduce this error.
I will leave the machine I reproduce it in future test.
