### ISSUE TITLE
nodetool broken with java-11-openjdk-11.0.10.0.9-0.fc33.x86_64

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-tools-java#235]
I see error messages like

```
Cannot initialize optimized memory deallocator. Some data, both in-memory and on-disk, may live longer due to garbage collection.
error: null
-- StackTrace --
java.lang.NullPointerException
    at org.apache.cassandra.config.DatabaseDescriptor.getDiskFailurePolicy(DatabaseDescriptor.java:1860)
    at org.apache.cassandra.utils.JVMStabilityInspector.inspectThrowable(JVMStabilityInspector.java:82)
    at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:104)
    at org.apache.cassandra.utils.FBUtilities.getToolsOutputDirectory(FBUtilities.java:824)
    at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:213)
    at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:179)
```

**Comment by avikivity** [comment]
Cassandra 3.11 appears to handle it better:

```java
    static
    {
        boolean canClean = false;
        try
        {
            ByteBuffer buf = ByteBuffer.allocateDirect(1);
            ((DirectBuffer) buf).cleaner().clean();
            canClean = true;
        }
        catch (Throwable t)
        {
            logger.error("Cannot initialize un-mmaper.  (Are you using a non-Oracle JVM?)  Compacted data files will not be removed promptly.  Consider using an Oracle JVM or using standard disk access mode", t);
            JVMStabilityInspector.inspectThrowable(t);
        }
        isCleanerAvailable = canClean;
    }

```
