### ISSUE TITLE
sstabledump unable to load schema

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla-tools-java#25]
Scylla version: master

sstabledump is unable to load the schema to process a sstable, and fails with a `NullPointerException`.

To repro, just create any table and insert some data:

```
echo "create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };" | $SCYLLA_TOOLS_HOME/bin/cqlsh
echo "create table ks.cf(p text, c text, v int, primary key (p, c));" |  $SCYLLA_TOOLS_HOME/bin/cqlsh
for i in `seq 1 1000`; do echo  "insert into ks.cf (p, c, v) values ('key1', '$i', 0);" ; done | $SCYLLA_TOOLS_HOME/bin/cqlsh
```

Trying to use sstabledump results in:

```
$SCYLLA_TOOLS_HOME/tools/bin/sstabledump $SCYLLA_DATA_DIR/ks/cf-aa2f2690120611e7aaaf000000000000/ks-cf-ka-1-Data.db
Exception in thread "main" java.lang.NullPointerException
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:471)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openNoValidation(SSTableReader.java:387)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:202)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)
```

Apparently, the column family metadata is null, which gets returned in `com.scylladb.tools.SSTableExport#metadataFromSSTable`, by `Schema.instance.getCFMetaData(desc)`. A few lines before we try to do a local query to load the schemas, but that obviously returns nothing.

**Comment by elcallio** [comment]
Was the cassandra.yaml used by the tool configured with the right "datadirs" setting, i.e. path to the scylla data dir?

**Comment by duarten** [comment]
It was not, I only found out about that later :/

I think the tool could a) give a more informative error in this case,
and/or b) assume it's pointed to a data directory and not a stranded data
file, and try to navigate that (i.e., automatically fill in the blanks).

**Comment by elcallio** [comment]
I can somewhat agree, but truth be told the cassandra tools and 
infrastructure is not super well suited to do that. :-P (Configuration 
from _within_ the program is awkward at best).

This is probably yet another reason, btw, why 3.x format sstables 
contain schema information and can be looked and operated on 
independently of the database  schemas.

**Comment by tgrabiec** [comment]
We're talking about sstabledump from scylla-tools package, that can be expected to work with default Scylla installation out of the box. 

Currently it doesn't and there's no hint why. `sstabledump -h` doesn't say anything about `cassandra.yaml`. Where should I put `cassandra.yaml` and what should it contain?

**Comment by duarten** [comment]
It's still not working for me with the following data change:

```diff
diff --git a/conf/cassandra.yaml b/conf/cassandra.yaml
index 085b68e..8f822db 100644
--- a/conf/cassandra.yaml
+++ b/conf/cassandra.yaml
@@ -166,8 +166,8 @@ partitioner: org.apache.cassandra.dht.Murmur3Partitioner
 # will spread data evenly across them, subject to the granularity of
 # the configured compaction strategy.
 # If not set, the default directory is $CASSANDRA_HOME/data/data.
-# data_file_directories:
-#     - /var/lib/cassandra/data
+data_file_directories:
+    - /home/duarten/code/scylla/tmp
```

Do I need to do anything else?

**Comment by tgrabiec** [comment]
@duarten What error do you get? Do you set any environment variables?

Setting CASSANDRA_CONF to point to a directory containing cassandra.yaml didn't work for me:

```
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
	at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:76)
	at org.apache.cassandra.config.YamlConfigurationLoader.<clinit>(YamlConfigurationLoader.java:90)
	at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:132)
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119)
	at org.apache.cassandra.tools.Util.initDatabaseDescriptor(Util.java:38)
	at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:24)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)
```
 
I worked around this like this:

```
export _JAVA_OPTIONS="-Dcassandra.config=file://$HOME/src/scylla/conf/cassandra.yaml"
```

The yaml was a copy of scylla.yaml, with scylla-specyfic options commented out.

**Comment by duarten** [comment]
I get the same NPE error:

```bash
$ sudo _JAVA_OPTIONS="-Dcassandra.config=file://$HOME/code/scylla-tools-java/conf/cassandra.yaml" tools/bin/sstabledump $HOME/code/scylla/tmp/ks/my_view-72aa74601fd811e784e0000000000000/ks-my_view-ka-2-Data.db
Picked up _JAVA_OPTIONS: -Dcassandra.config=file:///home/duarten/code/scylla-tools-java/conf/cassandra.yaml
Exception in thread "main" java.lang.NullPointerException
	at org.apache.cassandra.io.sstable.format.SSTableReader.open(SSTableReader.java:471)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openNoValidation(SSTableReader.java:387)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:202)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)
```

**Comment by duarten** [comment]
Ah, I realized the problem. I was trying to dump an sstable for a view, and the tool isn't loading views :/

**Comment by slivne** [comment]
we need this fixed for 2.1

**Comment by elcallio** [comment]
Fix what? The tool works as expected (albeit awkward). cassandra.yaml needs a pointer to the data dirs, and the yaml file needs to be in classpath. This is a launch/packaging issue, and I don't think it can be very safely fixed in code.

**Comment by slivne** [comment]
we need to support running sstabledump on view tables as well - if we do
not load views schemas currently lets load them

**Comment by duarten** [comment]
I think we could also improve the error message, and make the tool smarter and try to find the schema tables by assuming it was pointed to a file in a valid data directory.

**Comment by elcallio** [comment]
I've sent a patch with a more verbose error message. I have also verified that with correct config (i.e. datadirs), dumping views work fine.

**Comment by tgrabiec** [comment]
To run sstabledump in a Scylla deployment, I first need to run:
```sh
cat /etc/scylla/scylla.yaml | grep -v api_doc_dir | grep -v experimental | grep -v murmur3_partitioner_ignore_msb_bits | grep -v api_ui_dir | grep -v api_address | grep -v api_port > /etc/scylla/cassandra.yaml
export _JAVA_OPTIONS="-Dcassandra.config=file:///etc/scylla/cassandra.yaml"
```

**Comment by slivne** [comment]
@elcallio - can we run sstabledump on views ?

**Comment by elcallio** [comment]
@slivne If cassandra can load the view schema, yes, it should work. Also, if sstables are 3.0/mc format, there is no need at all for reading schemas. All required info is in sstable.

**Comment by slivne** [comment]
Works for me on 3.1.2

```
cqlsh> create KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use ks;
cqlsh:ks> CREATE TABLE buildings (
      ...     name text,
      ...     city text,
      ...     built int,
      ...     meters int,
      ...     PRIMARY KEY (name)
      ... );
cqlsh:ks> CREATE MATERIALIZED VIEW building_by_city AS
      ...         SELECT * FROM buildings
      ...         WHERE city IS NOT NULL
      ...         PRIMARY KEY(city, name);
cqlsh:ks> insert INTO buildings (name, city, built, meters) VALUES ('a','a',1900,1);
cqlsh:ks> select * from building_by_city ;

 city | name | built | meters
------+------+-------+--------
    a |    a |  1900 |      1

(1 rows)
```

```
sstabledump ks//building_by_city-45a633a0357411ea92c2000000000000/mc-2-big-Data.db 
WARN  19:48:02,821 Small cdc volume detected at /cdc_raw; setting cdc_total_space_in_mb to 1278.  You can override this in cassandra.yaml
[
  {
    "partition" : {
      "key" : [ "a" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 32,
        "clustering" : [ "a" ],
        "liveness_info" : { "tstamp" : "2020-01-12T19:47:14.338461Z" },
        "cells" : [
          { "name" : "built", "value" : 1900 },
          { "name" : "meters", "value" : 1 }
        ]
      }
    ]
  }
]
```
