### ISSUE TITLE
sstabledump exception on user-defined data type

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-tools-java#27]
CREATE TYPE name_type (firstname text, lastname text);
CREATE TYPE address_type (name frozen<name_type>, number int, street text, phones set<text>);
CREATE TABLE testdatatype (
                a ascii PRIMARY KEY,
                ...,
                t frozen<address_type>,
                u frozen<list<list<address_type>>>,
                ...,
            )
insert data:
{name: {firstname: 'name1', lastname: 'last1'}, number: 1, street: 'street 1', phones: {'1111 2222', '3333 4444'}}

sstabledump fails with exception:
Exception in thread "main" org.apache.cassandra.exceptions.InvalidRequestException: Unknown type ks.address_type
	at org.apache.cassandra.cql3.CQL3Type$Raw$RawUT.prepare(CQL3Type.java:745)
	at org.apache.cassandra.cql3.CQL3Type$Raw.prepareInternal(CQL3Type.java:533)
	at org.apache.cassandra.schema.CQLTypeParser.parse(CQLTypeParser.java:53)
	at org.apache.cassandra.schema.SchemaKeyspace.createColumnFromRow(SchemaKeyspace.java:1011)
	at org.apache.cassandra.schema.SchemaKeyspace.lambda$fetchColumns$12(SchemaKeyspace.java:995)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchColumns(SchemaKeyspace.java:995)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:949)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:928)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:891)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:868)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:856)
	at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:136)
	at org.apache.cassandra.config.Schema.loadFromDiskForTool(Schema.java:145)
	at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:26)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:37)
^CKeyboardInterrupt: KeyboardInterrupt()

**Comment by elcallio** [comment]
The above example works for me in current master. I recognize the error, and I think it was fixed though for the love of me I cannot remember where. :-P

**Comment by slivne** [comment]
@elcallio

just to be clear this is without using the code that you just submitted
that transfors our system tables to 3.X format (e.g. the test was done on
1.7 code)

**Comment by elcallio** [comment]
I double-checked that I don't have any weird changes in my scylla-tools-java repo. It works for me on the current master combo scylla/tools (whatever version number that might entail).
