### ISSUE TITLE
running sstablelevelreset as root caused the next running of the tool to fail with exception

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-tools-java#29]
1. create cluster
2. start cluster, run stress tool, then stop the cluster
3. run as root: sstablelevelreset --really-reset keyspace1 standard1
got error:
'ColumnFamily not found: keyspace1/standard1\n'
4. run the same as user:

$ ~/dev/scylla/resources/cassandra/tools/bin/sstablelevelreset --really-reset keyspace1 standard1
ERROR 14:29:50 [/home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log]  was not completed, trying to abort it now
ERROR 14:29:50 Failed to abort [/home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log] 
java.lang.RuntimeException: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:557) ~[main/:na]
	at org.apache.cassandra.io.util.FileUtils.appendAndSync(FileUtils.java:538) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplica.append(LogReplica.java:66) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.lambda$null$2(LogReplicaSet.java:186) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.append(LogReplicaSet.java:186) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogFile.addRecord(LogFile.java:301) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogFile.abort(LogFile.java:255) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:98) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogTransaction$TransactionTidier.run(LogTransaction.java:247) [main/:na]
	at org.apache.cassandra.db.lifecycle.LogTransaction$TransactionTidier.tidy(LogTransaction.java:231) [main/:na]
	at org.apache.cassandra.utils.concurrent.Ref$GlobalState.release(Ref.java:320) [main/:na]
	at org.apache.cassandra.utils.concurrent.Ref$State.ensureReleased(Ref.java:198) [main/:na]
	at org.apache.cassandra.utils.concurrent.Ref.ensureReleased(Ref.java:118) [main/:na]
	at org.apache.cassandra.db.lifecycle.LogTransaction.complete(LogTransaction.java:359) [main/:na]
	at org.apache.cassandra.db.lifecycle.LogTransaction.doAbort(LogTransaction.java:376) [main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144) [main/:na]
	at org.apache.cassandra.db.lifecycle.LifecycleTransaction.doAbort(LifecycleTransaction.java:234) [main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144) [main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:193) [main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.close(Transactional.java:158) [main/:na]
	at org.apache.cassandra.db.Memtable.createFlushWriter(Memtable.java:449) [main/:na]
	at org.apache.cassandra.db.Memtable.writeSortedContents(Memtable.java:371) [main/:na]
	at org.apache.cassandra.db.Memtable.flush(Memtable.java:332) [main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1063) [main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_121]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_121]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_121]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_121]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_121]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_121]
	at java.nio.file.Files.write(Files.java:3351) ~[na:1.8.0_121]
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:550) ~[main/:na]
	... 30 common frames omitted
ERROR 14:29:50 Unable to delete /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log as it does not exist
ERROR 14:29:50 Error in ThreadPoolExecutor
java.lang.RuntimeException: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:557) ~[main/:na]
	at org.apache.cassandra.io.util.FileUtils.appendAndSync(FileUtils.java:538) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplica.append(LogReplica.java:66) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.lambda$null$2(LogReplicaSet.java:186) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.append(LogReplicaSet.java:186) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogFile.addRecord(LogFile.java:301) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogFile.abort(LogFile.java:255) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103) ~[main/:na]
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:98) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LogTransaction.doAbort(LogTransaction.java:376) ~[main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144) ~[main/:na]
	at org.apache.cassandra.db.lifecycle.LifecycleTransaction.doAbort(LifecycleTransaction.java:234) ~[main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144) ~[main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:193) ~[main/:na]
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.close(Transactional.java:158) ~[main/:na]
	at org.apache.cassandra.db.Memtable.createFlushWriter(Memtable.java:449) ~[main/:na]
	at org.apache.cassandra.db.Memtable.writeSortedContents(Memtable.java:371) ~[main/:na]
	at org.apache.cassandra.db.Memtable.flush(Memtable.java:332) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1063) ~[main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_121]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_121]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_121]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_121]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_121]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[na:1.8.0_121]
	at java.nio.file.Files.write(Files.java:3351) ~[na:1.8.0_121]
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:550) ~[main/:na]
	... 24 common frames omitted
Exception in thread "MemtableFlushWriter:2" java.lang.RuntimeException: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:557)
	at org.apache.cassandra.io.util.FileUtils.appendAndSync(FileUtils.java:538)
	at org.apache.cassandra.db.lifecycle.LogReplica.append(LogReplica.java:66)
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.lambda$null$2(LogReplicaSet.java:186)
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113)
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103)
	at org.apache.cassandra.db.lifecycle.LogReplicaSet.append(LogReplicaSet.java:186)
	at org.apache.cassandra.db.lifecycle.LogFile.addRecord(LogFile.java:301)
	at org.apache.cassandra.db.lifecycle.LogFile.abort(LogFile.java:255)
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:113)
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:103)
	at org.apache.cassandra.utils.Throwables.perform(Throwables.java:98)
	at org.apache.cassandra.db.lifecycle.LogTransaction.doAbort(LogTransaction.java:376)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144)
	at org.apache.cassandra.db.lifecycle.LifecycleTransaction.doAbort(LifecycleTransaction.java:234)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:144)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.abort(Transactional.java:193)
	at org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.close(Transactional.java:158)
	at org.apache.cassandra.db.Memtable.createFlushWriter(Memtable.java:449)
	at org.apache.cassandra.db.Memtable.writeSortedContents(Memtable.java:371)
	at org.apache.cassandra.db.Memtable.flush(Memtable.java:332)
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: /home/larisau/dev/scylla-tools-java/data/data/system/local-7ad54392bcdd35a684174e047860b377/mc_txn_flush_298c1900-1943-11e7-889a-8d0c97517e62.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3351)
	at org.apache.cassandra.io.util.FileUtils.write(FileUtils.java:550)

**Comment by slivne** [comment]
@larisau if this is not run with root is this still an issue ?

**Comment by avikivity** [comment]
It may also cause scylladb to fail to start, depending on root's umask.

**Comment by avikivity** [comment]
sstablelevelreset just creates some files under the root user, which the scylla user can't read.

**Comment by larisau** [comment]
It happens only if we run it as root.
We have such test in dtest, it's not failing currently:
http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-dtest/lastBuild/label=monster,mode=release,smp=1/testReport/offline_tools_test/

**Comment by slivne** [comment]
I agree this is not a bug - if you run a tool with root it will creates files with root user that may not be accessible afterwords (this is normal). 

This is not the same as in issue #26 in which there is an expectation that files will not be changed - and they are changed.
