### ISSUE TITLE
cassandra-stress counter_write: the table Counter1 is not created automatically

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-tools-java#32]
cassandra-stress with counters creates only Standard1 table, but Counter1 table is not created.

[root@ip-172-30-0-39 ~]# /usr/bin/cassandra-stress counter_write n=1000
WARN  09:36:05 You listed localhost/0:0:0:0:0:0:0:1:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
Connected to cluster: larisa-test-aws-scylla-db-cluster-4fb207b4, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
Datatacenter: datacenter1; Host: /172.30.0.160; Rack: rack1
Created keyspaces. Sleeping 1s for propagation.
Sleeping 2s...
Warming up COUNTER_WRITE with 250 iterations...
Failed to connect over JMX; not collecting these stats
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table counter1
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:98)
	at org.apache.cassandra.stress.util.JavaDriverClient.prepare(JavaDriverClient.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation$JavaDriverWrapper.createPreparedStatement(CqlOperation.java:311)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:74)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:258)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table counter1
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chan4est** [comment]
+1 for this issue.
