### ISSUE TITLE
cassandra-stress with -log hdrfile options failed with error  java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-tools-java#328]
Cassandra stress command with option `-log hdrfile= ` and ru failed with next error:
./share/cassandra/bin/cassandra-stress write n=40000 -log hdrfile=/home/abykov/tmp/test.hdr interval=1s -node 172.17.0.2

```
Exception in thread "StressMetrics" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:135)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:154)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:175)
	at org.apache.cassandra.stress.report.StressMetrics.logHistogram(StressMetrics.java:336)
	at org.apache.cassandra.stress.report.StressMetrics.logHistograms(StressMetrics.java:320)
	at org.apache.cassandra.stress.report.StressMetrics.recordInterval(StressMetrics.java:253)
	at org.apache.cassandra.stress.report.StressMetrics.reportingLoop(StressMetrics.java:172)
	at org.apache.cassandra.stress.report.StressMetrics.lambda$new$1(StressMetrics.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
```
This happend for java versions: 11, 17, 19.
This option works correctly only with 8

**Comment by aleksbykov** [comment]
Steps to reproduce:
1. run scylla (in docker)
2. execute c-s
3. cassandra-stress write n=40000 -log hdrfile=test.hdr interval=1s -node 172.17.0.2
Command failed with error

**Comment by mykaul** [comment]
https://github.com/scylladb/scylla-tools-java/pull/326 ?

**Comment by roydahan** [comment]
@aleksbykov the issue & the fix that @mykaul referenced is exactly what I meant.
Now, if it's still not working after this fix (please make sure the version you use includes the fix), please reopen the original issue or report here.

**Comment by fruch** [comment]
I can confirm it's now working with master docker image (that we use in SCT)
