### ISSUE TITLE
When loading table via sstableloader while destination table doesn't exist on Scylla, there's no error or log message about an error/failure

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-tools-java#35]
The prompt just returns immediately.

Scylla version 1.7.1

Scylla destination has mykeyspace, but simple_table was not created.

sstableloader -v -d 10.240.0.28 /home/tomer/.ccm/tomer/node1/data0/mykeyspace/simple_table-81598ff0510b11e792e015d3f6fafe0a/

**Comment by dorlaor** [comment]
Scylla version?
Please give full details such as cmdline too

**Comment by tomer-sandler** [comment]
I'm unable to reproduce the issue, I'm now getting the following error:

[tomer@tomer-cassandra-3-10-ccm ~]$ sstableloader -v -d 10.240.0.28 /home/tomer/.ccm/tomer/node1/data0/mykeyspace/simple_table-81598ff0510b11e792e015d3f6fafe0a/
WARN  07:02:57 Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
java.lang.NullPointerException
        at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:423)
        at com.scylladb.tools.SSTableToCQL.getCFMetaData(SSTableToCQL.java:792)
        at com.scylladb.tools.SSTableToCQL.addFile(SSTableToCQL.java:831)
        at com.scylladb.tools.SSTableToCQL.access$100(SSTableToCQL.java:108)
        at com.scylladb.tools.SSTableToCQL$1.accept(SSTableToCQL.java:809)
        at java.io.File.list(File.java:1161)
        at com.scylladb.tools.SSTableToCQL.openSSTables(SSTableToCQL.java:803)
        at com.scylladb.tools.SSTableToCQL.stream(SSTableToCQL.java:883)
        at com.scylladb.tools.BulkLoader.main(BulkLoader.java:840)

Still I would argue that the error message is not clear...

**Comment by tomer-sandler** [comment]
Seems to be testing error. Closing ticket.
