### ISSUE TITLE
sstabledump doesn't work for system_schema.scylla_tables sstables

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-tools-java#91]
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not locate schema info for /home/tgrabiec/.ccm/scylla-3/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/la-1203-big/(system_schema:scylla_tables). Make sure your 'data_file_directories' is pointed correctly.
	at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:30)
	at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
	at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

**Comment by haaawk** [comment]
Have you tried setting `data_file_directories` in conf/cassandra.yaml in tools to the data directory? It helped for me.
